include include/rules.mak

all:
	$(MAKEC) gcc
	$(MAKEC) toolstdc



clean :
	$(MAKEC) toolstdc  clean
	$(MAKEC) nasklib   clean
	$(MAKEC) go_lib    clean
	$(MAKEC) libiberty clean
	$(MAKEC) intl      clean
	$(MAKEC) gcc       clean
	$(MAKEC) drv_stdc  clean
	$(MAKEC) cp  clean


